import './globals.css'
import '../components/ConsentPopUp.module.css'
import MainFooter from '../components/MainFooter'
import ConsentPopUp from '../components/ConsentPopUp'

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body>
                <header></header>
                <main>{children}</main>
                <footer>
                    <MainFooter />
                </footer>
                <ConsentPopUp />
            </body>
        </html>
    )
}
