import '../styles/globals.css'
import '../components/ConsentPopUp.module.css'
import MainFooter from '../components/MainFooter'
import PrincessForm from '../components/PrincessForm'
import '../components/PrincessForm.module.css'
import ConsentPopUp from '../components/ConsentPopUp'
import CookiesProvider from './cookies'

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <CookiesProvider>
                <body>
                    <header></header>
                    <main>{children}</main>
                    <footer>
                        <MainFooter />
                    </footer>
                    <ConsentPopUp />
                </body>
            </CookiesProvider>
        </html>
    )
}
